server:
  port: 6010

spring:
  application:
    name: messageservice
  datasource:
    url: jdbc:mysql://localhost:3306/messageservice
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

    jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false

#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.messaging: DEBUG
#    com.example.messaging_service: DEBUG
