server:
  port: 8888

spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "my_secret_key_which_should_be_very_long_and_secure" # Sử dụng secret key trực tiếp cho JWT

  cloud:
    gateway:
      routes:
        - id: UserService
          uri: http://localhost:8080
          predicates:
            - Path=/addresses/user/**, /users, /users/{userId}

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.web.reactive.function.client: DEBUG
#    reactor.netty.http.client: DEBUG
#    org.springframework.security: DEBUG
