#server:
#  port: 6006
#
#spring:
#  application:
#    name: orderservice
#  r2dbc:
#    url: r2dbc:pool:mysql://localhost:3306/orderservice
#    username: root
#    password:
#  liquibase:
#    url: jdbc:mysql://localhost:3306/orderservice
#    enabled: true
#    user: root
#    password:
#    change-log: classpath:db/changelog/changelog-master.xml
#  kafka:
#    producer:
#      retries: 3
#      batch-size: 16384
#      buffer-memory: 33554432
#    consumer:
#      session.timeout.ms: 45000
#      heartbeat.interval.ms: 15000
#
#
#kafka:
#  bootstrap:
#    servers: localhost:9092
#  consumer:
#    group.initial.rebalance.delay.ms: 3000  # Thêm dòng này
#
#payment:
#  kafka:
#    consumer-group-id: paymentService-groupId
#
##logging:
##  level:
##    io.r2dbc.spi: DEBUG
##    dev.miku.r2dbc.mysql: DEBUG
##    org.springframework.data.r2dbc: DEBUG



server:
  port: 6006

spring:
  application:
    name: orderservice
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/orderservice
    username: root
    password:
  liquibase:
    url: jdbc:mysql://localhost:3306/orderservice
    enabled: true
    user: root
    password:
    change-log: classpath:db/changelog/changelog-master.xml
  kafka:
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      session.timeout.ms: 30000
      heartbeat.interval.ms: 10000
      max.poll.interval.ms: 300000

kafka:
  bootstrap:
    servers: localhost:9092
  consumer:
    group.initial.rebalance.delay.ms: 3000

payment:
  kafka:
    consumer-group-id: orderService-groupId
