server:
  port: 6004

spring:
  application:
    name: cartservice
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/cartservice
    username: root
    password:
  liquibase:
    url: jdbc:mysql://localhost:3306/cartservice
    enabled: true
    user: root
    password:
    change-log: classpath:db/changelog/changelog-master.xml
  kafka:
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      session.timeout.ms: 30000
      heartbeat.interval.ms: 10000
      max.poll.interval.ms: 300000

kafka:
  bootstrap:
    servers: localhost:9092
  consumer:
    group.initial.rebalance.delay.ms: 3000

payment:
  kafka:
    consumer-group-id: cartService-groupId
